{% set name = "km3io" %}
{% set version = "0.25.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/km3io-{{ version }}.tar.gz
  sha256: bce1a5b2173c17cfa851cd6e5ce7996a5d1ab0172b289ea2a2a44d15e468207c

build:
  number: 0
  noarch: python
  entry_points:
    - KPrintTree=km3io.utils.kprinttree:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools_scm
  run:
    - awkward >=1.0.0rc2
    - awkward0
    - docopt
    - numba >=0.50
    - python >=3.6
    - setuptools-scm
    - uproot >=4.0.0rc5
    - uproot3 >=3.11.1

test:
  imports:
    - km3io
  commands:
    - pip check
    - KPrintTree --help
  requires:
    - pip

about:
  home: http://git.km3net.de/km3py/km3io
  summary: KM3NeT I/O without ROOT
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tamasgal
