{% set name = "km3io" %}
{% set version = "1.2.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/km3io-{{ version }}.tar.gz
  sha256: ffbeebe0a16c061f1784a45568396ad4627813b895587e090bf7223a4a9bdd78

build:
  number: 0
  noarch: python
  entry_points:
    - KPrintTree=km3io.utils.kprinttree:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.9
    - setuptools_scm
  run:
    - awkward >=2
    - docopt
    - numba >=0.50
    - numpy >=2
    - python >=3.9
    - setuptools-scm
    - uproot >=5

test:
  imports:
    - km3io
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://git.km3net.de/km3py/km3io
  summary: KM3NeT I/O without ROOT
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tamasgal
